/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Custom
 */
interface Custom {
  /** the code associated with the error returned */
  code: number;
  /** detailed message about the error returned */
  message: string;
}

export class CustomError extends ApiError<Custom> {}
