/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { PetTypeEnum, petTypeEnumSchema } from './petTypeEnum';

export interface NewPet {
  /** the name lovingly given to the pet */
  name: string;
  /** the type of pets allowed */
  type?: PetTypeEnum;
}

export const newPetSchema: Schema<NewPet> = object({
  name: ['name', string()],
  type: ['type', optional(petTypeEnumSchema)],
});
