/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';
import { PetTypeEnum, petTypeEnumSchema } from './petTypeEnum';

export interface Pet {
  /** the name lovingly given to the pet */
  name: string;
  /** the type of pets allowed */
  type?: PetTypeEnum;
  /** a unique identifier for a Pet */
  id: bigint;
}

export const petSchema: Schema<Pet> = object({
  name: ['name', string()],
  type: ['type', optional(petTypeEnumSchema)],
  id: ['id', bigint()],
});
