/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PetTypeEnum
 */
export enum PetTypeEnum {
  Dog = 'dog',
  Cat = 'cat',
}

/**
 * Schema for PetTypeEnum
 */
export const petTypeEnumSchema: Schema<PetTypeEnum> = stringEnum(PetTypeEnum);
